config/routes.rb
Rails.application.routes.draw do
  root 'pages#show'
  get 'conventions/search', to: 'conventions#search'
  get 'games/search', to: 'games#search'
  get 'matches/search', to: 'matches#search'
  get 'participations/search', to: 'participations#search'
  get 'players/search', to: 'players#search'
  get 'teams/search', to: 'teams#search'
  
  resources :pages, :only=>:show
  resources :games
  resources :teams
  resources :players
  resources :conventions
  resources :matches
  resources :participations
end

app/models/participation.rb
class Participation < ActiveRecord::Base
  belongs_to :match
  belongs_to :player
  # validates_presence_of :player_id,:message => "Gracz jest wymagany"
  validates_presence_of :match_id, :message => "Rozgrywka jest wymagana"
end

app/controllers/participations_controller.rb
#zrobic zeby tworzyło się normalnie tak jak kazy inny obiekt żeby routy nie były zależne od graczy
#zastanowic sie czy zrobic uczestnictwa u gracza do edycji czy tylko do wyswietlania
#póki co mozna zostawic tak jak jest
#w przypadku reszty najlepiej narazie zrobic tylko wyswietlanie powiazanych obiektów
class ParticipationsController < ApplicationController

  def edit
    @change_participation = Participation.find(params[:id])
  end

  def update
    @change_participation = Participation.find(params[:id])
    if  @change_participation.update_attributes(participation_params)
      redirect_to participations_path
    else
      render 'edit'
    end
  end

  def show
    @participation = Participation.find(params[:id])
  end
#dodac tez wypisywanie wszystkich dostepnych uczestnictw
  def index
      @all_participation = Participation.all
      if params[:player_id]!=nil
        @player= Player.find(params[:player_id])
      else
        @player=nil
      end
  end

  def new
    @new_participation = Participation.new
  end
# niech wybiera z dostepnych za pomoca radio buttona wypisujemy wszystkie rozgrywki jakie sa i gracz sobie wybiera ten interesujacy go
  def create
      #numer= params[:participation][:match_id]
      @new_participation = Participation.new(participation_params)
      if @new_participation.save
      number_of_players = Participation.count(numer)
      number_of_seats = Match.find(numer).seats_number
      if number_of_players < number_of_seats
        @new_participation = Participation.new(participation_params)
        @new_participation.save
        redirect_to participations_path
      else
        #@player = Player.find(params[:player_id])
        render 'new'
      end
    else
      #@player = Player.find(params[:player_id])
      render 'new'
  end
  end

  def destroy
    if Participation.destroy(params[:id])
      redirect_to matches_path
    else
      flash[:error] = "Nie można usunąć - w rozgrywce biorą udział gracze"
      redirect_to matches_path
    end
  end

  def search
    @player = Player.where("nickname ~* ?", "#{params[:text]}[a-b]*")
    @player.each do |g|
     @participation = Participation.where(player_id: g.id)
     break
    end
  end

  def participation_params
    params.require(:participation).permit(:player_id,:match_id)
  end
end

app/helpers/participation_helper.rb
module ParticipationHelper
end

app/helpers/participations_helper.rb
module ParticipationsHelper
end

app/views/participations/edit.html.erb
<body class="participations">
<%= form_for @change_participation do |p| %>
<%if @change_participation.errors.any? %>
<% @change_participation.errors.each do |attr,msg|  %>
<div class="message-box"><%=msg%></div>
<%end%>
<%end%>
  <%= p.label "Wybierz gracza" %> <br>
  <%= p.collection_select :player_id, Player.all, :id, :nickname, {prompt: Player.find_by_id(:player_id)}, {class: "select-tab"}%>
  <%= p.label "Wybierz gre:" %><br>
  <%= p.collection_select :match_id, Match.all, :id, :id, {prompt: :match_id}, {class: "select-tab"} %>
  <%= p.submit "Accept", class: 'submit-style' %>
<%end%>
  <%= debug(params) %>
</body>

app/views/participations/index.html.erb
<body class="participations">
<% if @player!=nil %>
  <div><%= link_to("Uczestnicz w meczu", new_player_participation_path(@player) )%> </div> <br>
<%end%>
  <ul class="title-list">
    <li class="title-ele"> Gracz </li>
    <li class="title-ele" > Match </li>
    <li class="title-ele" style="width: 220px"> Create </li>
    <li class="title-ele"> Delete </li>
    <li class="title-ele"> Show </li>
    <li class="title-ele"> Edit </li>
  </ul>
  <% if @player!=nil %>
  <%else%>
  <% @all_participation.each do |p| %>
  <ul class="name-list">
    <li class="name-list"><div class="name-list"><%= Player.find(p.player_id).nickname %></div> </li>
    <li class="name-list"><div class="name-list"><%= p.match_id %></div></div> </li>
    <li class="name-list" style="width: 220px"><div class="name-list" style="width: 220px"><%= p.created_at %></div> </li>
    <li class="name-list"><div class="name-list"><%=link_to("Usuń", participation_path(p), method: :delete) %></div> </li>
    <li class="name-list"><div class="name-list"><%=link_to("Wyświetl",participation_path(p)) %></div> </li>
    <li class="name-list"><div class="name-list"><%= link_to("Edytuj", edit_participation_path(p)) %></div> </li>
    <br>
    <br>
  </ul>
    <%end%>
    <%end%>
</body>

app/views/participations/new.html.erb
<body class="participations">
<%= form_for @new_participation do |p| %>
<%if @new_participation.errors.any? %>
<% @new_participation.errors.each do |attr,msg|  %>
<div class="message-box"><%=msg%></div>
<br>
<% end %>
<%end %>
  <%= p.label "Wybierz gracza" %><br>
  <%= p.collection_select :player_id, Player.all, :id, :nickname, {prompt: "Wybierz"}, {class: "select-tab"}%>
  <%= p.label "Wybierz gre:" %> <br>
  <%= p.collection_select :match_id, Match.all, :id, :id, {prompt: "Wybierz"}, {class: "select-tab"} %>
  <%= p.submit "Accept", class: 'submit-style'%>
<%end%>
  <%= debug(params) %>
</body>

app/views/participations/search.html.erb
<body class="participations">
  <ul class="title-list">
    <li class="title-ele"> Gracz </li>
    <li class="title-ele" > Match </li>
    <li class="title-ele" style="width: 220px"> Create </li>
  </ul>
  <% @participation.each do |p| %>
  <ul class="name-list">
    <li class="name-list"><div class="name-list"><%= Player.find(p.player_id).nickname %></div> </li>
    <li class="name-list"><div class="name-list"><%= p.match_id %></div></div> </li>
    <li class="name-list" style="width: 220px"><div class="name-list" style="width: 220px"><%= p.created_at %></div> </li>
    <br>
    <br>
  </ul>
    <%end%>
</body>

app/views/participations/show.html.erb
<body class="participations" >

<div> Nazwa gracza: <%= Player.find(@participation.player_id).name %> </div>
<div> Id rzogrywki: <%= Match.find(@participation.match_id).id %> </div>
<div> Data utworzenia: <%= @participation.created_at %> </div>

<%= link_to("Wróć",player_participations_path(Player.find(@participation.player_id))) %>
</body>