config/routes.rb
Rails.application.routes.draw do
  root 'pages#show'
  get 'conventions/search', to: 'conventions#search'
  get 'games/search', to: 'games#search'
  get 'matches/search', to: 'matches#search'
  get 'participations/search', to: 'participations#search'
  get 'players/search', to: 'players#search'
  get 'teams/search', to: 'teams#search'
  
  resources :pages, :only=>:show
  resources :games
  resources :teams
  resources :players
  resources :conventions
  resources :matches
  resources :participations
end

app/models/player.rb
class Player < ActiveRecord::Base
  belongs_to :team
  has_many :participation
  before_destroy :check_for_participations

  #presence
  validates_presence_of :nickname, :message => "Nick jest wymagany", :allow_nil => true
  validates_presence_of :name, :message => "Nazwa jest wymagana", :allow_nil => true
  validates_presence_of :surname, :message => "Nazwisko jest wymagane", :allow_nil => true
  validates_presence_of :age, :message => "Wiek jest wymagany"
  validates_presence_of :team_id, :message => "Drużyna jest wymagana"

  #format
  validates_format_of :nickname, with: /\p{Alpha}/, :message => "Nick musi zawierać litery", :allow_blank =>true
  validates_format_of :name, with: /\p{Alpha}/, :message => "Imię musi zawierać litery", :allow_blank => true
  validates_format_of :surname, with: /\p{Alpha}/, :message => "Nazwisko musi zawierać lietry", :allow_blank =>true
  validates_numericality_of :age, :integer_only => true, :message => "Wiek musi być liczbą", :allow_blank => true
  validates_numericality_of :age, :less_than => 100, :message => "Wiek musi być mniejszy niż 100", :allow_blank => true

  #unikatowość

  #długość
  validates_length_of :nickname, :maximum => 15, :message => "Nick jest za długi", :allow_blank => true
  validates_length_of :name, :maximum => 15, :message => "Imię jest za długie", :allow_blank => true
  validates_length_of :surname, :maximum => 15, :message => "Nazwisko jest za długie", :allow_blank =>true

  private

  def check_for_participations
    if participation.any?
      return false
    end
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController

  def edit
    @change_player = Player.find(params[:id])
  end

  def update
    @change_player = Player.find(params[:id])
    if @change_player.update_attributes(player_params)
      redirect_to players_path
    else
      render 'edit'
    end
  end

  def show
    @player = Player.find(params[:id])
  end

  def index
    @all_player = Player.all
    @all_participations = Participation.all
  end

  def new
    @new_player = Player.new
  end

  def create
    @new_player= Player.new(player_params)
      if @new_player.save
        redirect_to players_path
      else
        render 'new'
      end
  end

  def destroy
    if Player.destroy(params[:id])
      redirect_to players_path
    else
      flash[:error] = "Nie można usunąć - gracz bierze udział w rozgrywce"
      redirect_to players_path
    end
  end

  def search
    @player = Player.where("nickname ~* ?", "#{params[:text]}[a-b]*")
    @all_participations = Participation.all
  end

  def player_params #umozliwia dostep do atrybutow stosowany do obrony danych przed innymi uzytkownikami
    params.require(:player).permit(:nickname,:name,:surname,:age,:team_id)
  end

end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/edit.html.erb
<body class="player">
<%= form_for @change_player do |f|%>
<%if @change_player.errors.any? %>
<% @change_player.errors.each do |attr,msg|  %>
<div class="message-box"><%=msg%></div>
<% end %>
<%end %>
  <%= f.label "Nick:" %><br>
  <%= f.text_field :nickname, class: "input-style" %>
  <%= f.label "Imię:" %><br>
  <%= f.text_field :name, class: "input-style" %>
  <%= f.label "Nazwisko:" %><br>
  <%= f.text_field :surname, class: "input-style" %>
  <%= f.label "Wiek:" %><br>
  <%= f.text_field :age, class: "input-style" %><br>
  <%= f.label "Nazwa drużyny:" %><br>
  <%= f.collection_select :team_id,Team.all,:id, :name,{ prompt: "Wybierz"},{ class: "select-tab"} %>

  <%= f.submit "Accept", class: 'submit-style' %>

<%end%>
</body>

app/views/players/index.html.erb
<body class="player">

  <% if flash[:error] %>
    <div class="message-box"><%=flash[:error] %></div>
  <%end%>
<ul class="title-list">
    <li class="title-ele"> Nickname </li>
    <li class="title-ele"> Imię </li>
    <li class="title-ele"> Nazwisko </li>
    <li class="title-ele"> Wiek </li>
    <li class="title-ele"> Team </li>
    <li class="title-ele"> Usuń </li>
    <li class="title-ele"> Wyświetl </li>
    <li class="title-ele"> Edytuj </li>
    <li class="title-ele"> Mecz </li>
  </ul>
<% @all_player.each do |p| %>
<ul class="name-list">
  <li class="name-list"> <%= p.nickname %> </li>
  <li class="name-list"> <%=p.name %> </li>
  <li class="name-list"> <%=p.surname %> </li>
  <li class="name-list"> <%= p.age %> </li>
  <li class="name-list"> <%= Team.find(p.team_id).name %> </li>
  <li class="name-list"> <%= link_to("Usuń", player_path(p),method: :delete) %> </li>
  <li class="name-list">  <%= link_to("Wyświetl", player_path(p)) %> </li>
  <li class="name-list"> <%=link_to("Edytuj",edit_player_path(p)) %> </li>
  <li class="name-list"><div class="name-list"> <button class="button" onclick="loadDoc(this,'test',number)" >Wyswietl</button></div></li>
    <div class="present">
      <% @all_participations.each do |m| %>
      <% if m.player_id == p.id %>
            <br>
            <br>
      <ul class="under-ele">
        <li class="under-ele"><div class="under-ele"> <%= Match.find_by_id(m.match_id).time %></div> </li>
        <li class="under-ele"> <div class="under-ele"><%= Match.find_by_id(m.match_id).seats_number %></div> </li>
        <li class="under-ele"> <div class="under-ele"><%= Match.find_by_id(m.match_id).price %></div> </li>
        <% @mat = Match.find_by_id(m.match_id) %>
        <li class="under-ele"><div class="under-ele"> <%= Convention.find_by_id(@mat.convention_id).name %></div>  </li>
        <li class="under-ele"><div class="under-ele"> <%= Convention.find_by_id(@mat.game).name %></div>  </li>
      </ul>

      <% end %>
      <%end%>
    </div>
</ul>
<br>
<br>
<%end%>
<br>

</body>

app/views/players/new.html.erb
<body class="player">
<%= form_for @new_player do |f|%>
<%if @new_player.errors.any? %>
<% @new_player.errors.each do |attr,msg|  %>
<div class="message-box"><%=msg%></div>
<% end %>
<%end %>
  <%= f.label "Nick:" %><br>
  <%= f.text_field :nickname, class: "input-style" %>
  <%= f.label "Imię:" %><br>
  <%= f.text_field :name, class: "input-style" %>
  <%= f.label "Nazwisko:" %><br>
  <%= f.text_field :surname, class: "input-style" %>
  <%= f.label "Wiek:" %><br>
  <%= f.text_field :age, class: "input-style" %><br>
  <%= f.label "Nazwa drużyny:" %><br>
  <%= f.collection_select :team_id,Team.all,:id, :name, {prompt: "Wybierz"}, {class: "select-tab"} %>

  <%= f.submit "Accept", class: 'submit-style' %>

<%end%>
</body>

app/views/players/search.html.erb
<body class="player">
<center><p1> Wyszukiwanie: </p1></center>
<ul class="title-list">
    <li class="title-ele"> Nickname </li>
    <li class="title-ele"> Imię </li>
    <li class="title-ele"> Nazwisko </li>
    <li class="title-ele"> Wiek </li>
    <li class="title-ele"> Team </li>
    <li class="title-ele"> Rozgrywki </li>
  </ul>
<% @player.each do |p| %>
<ul class="name-list">
  <li class="name-list"> <%= p.nickname %> </li>
  <li class="name-list"> <%=p.name %> </li>
  <li class="name-list"> <%=p.surname %> </li>
  <li class="name-list"> <%= p.age %> </li>
  <li class="name-list"> <%= Team.find(p.team_id).name %> </li>
  <li class="name-list"><div class="name-list"> <button class="button" onclick="loadDoc(this,'test',number)" >Wyswietl</button></div></li>
    <div class="present">
      <% @all_participations.each do |m| %>
      <% if m.player_id == p.id %>
            <br>
            <br>
      <ul class="under-ele">
        <li class="under-ele"><div class="under-ele"> <%= Match.find_by_id(m.match_id).time %></div> </li>
        <li class="under-ele"> <div class="under-ele"><%= Match.find_by_id(m.match_id).seats_number %></div> </li>
        <li class="under-ele"> <div class="under-ele"><%= Match.find_by_id(m.match_id).price %></div> </li>
        <% @mat = Match.find_by_id(m.match_id) %>
        <li class="under-ele"><div class="under-ele"> <%= Convention.find_by_id(@mat.convention_id).name %></div>  </li>
        <li class="under-ele"><div class="under-ele"> <%= Convention.find_by_id(@mat.game).name %></div>  </li>
      </ul>

      <% end %>
      <%end%>
    </div>
</ul>
<br>
<br>
<%end%>
<br>
</body>

app/views/players/show.html.erb
<body class="player">

<div> Nick: <%= @player.nickname %> </div>
<div> Imię: <%= @player.name %> </div>
<div> Nazwisko: <%= @player.surname %> </div>
<div> Wiek: <%= @player.age %> </div>
<div> Drużyna: <%= Team.find(@player.team_id).name %> </div>

<%=link_to("Wróć",teams_path) %>