config/routes.rb
Rails.application.routes.draw do
  root 'pages#show'
  get 'conventions/search', to: 'conventions#search'
  get 'games/search', to: 'games#search'
  get 'matches/search', to: 'matches#search'
  get 'participations/search', to: 'participations#search'
  get 'players/search', to: 'players#search'
  get 'teams/search', to: 'teams#search'
  
  resources :pages, :only=>:show
  resources :games
  resources :teams
  resources :players
  resources :conventions
  resources :matches
  resources :participations
end

app/models/match.rb
class Match < ActiveRecord::Base
  belongs_to :game
  belongs_to :convention
  has_many :participation
  before_destroy :check_for_participations

  #presence
  validates_presence_of :time, :message => "Czas jest wymagany"
  validates_presence_of :seats_number, :message => "Liczba miejsc jest wymagana"
  validates_presence_of :price,:message => "Nagroda jest wymagana"
  validates_presence_of :game_id,:message => "Gra jest wymagana"
  validates_presence_of :convention_id,:message => "Konwent jest wymagany"

  #format
  validates_numericality_of :time, :integer_only => true, :message => "Czas musi być liczbą", :allow_blank => true
  validates_numericality_of :time, :less_than => 10, :message => "Czas musi być mniejszy niż 10", :allow_blank => true
  validates_numericality_of :seats_number, :less_than => 10, :message => "Liczba miejsc taka jak gry", :allow_blank => true #do pr
  validates_numericality_of :price, :integer_only => true, :message => "Cena musi być liczbą", :allow_blank => true

  private

  def check_for_participations
    if participation.any?
      return false
    end
  end

end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController

  def edit
    @change_match = Match.find(params[:id])
  end

  def update
    @change_match = Match.find(params[:id])
    if @change_match.update_attributes(match_params)
      redirect_to games_path
    else
      flash[:alert]="Failed editing"
      render 'edit'
    end
  end

  def show
    @match = Match.find(params[:id])
  end

  def index
    @all_matches = Match.all
    @indeks = 0
  end

  def new
    @match = Match.new
  end

  def create
    @match = Match.new(match_params)
    if @match.save
      redirect_to matches_path
    else
      # @match = Match.new
      flash[:alert]="Failed creating"
      render 'new'
    end
  end

  def destroy
    if Match.destroy(params[:id])
      redirect_to matches_path
    else
      flash[:error] = "Nie można usunąć - w rozgrywce biorą udział gracze"
      redirect_to matches_path
    end
  end

  def search
    @game = Game.where("name ~* ?", "#{params[:text]}[a-b]*")
    @game.each do |g|
     @match = Match.where(game_id: g.id) #zeby zwracalo zbiór rekordów a nie jeden bo w view robimy .each
     break
    end
  end

  def match_params
    params.require(:match).permit(:time,:seats_number,:price,:game_id,:convention_id)
  end
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/views/matches/edit.html.erb
<body class="matches">

<%= form_for @change_match do |m| %>
<%if @change_match.errors.any? %>
<% @change_match.errors.each do |attr,msg|  %>
<div class="message-box"><%=msg%></div>
<% end %>
<%end %>
  <% flash.clear %>
  <%= m.label "Czas" %><br>
  <%= m.text_field :time, class: "input-style" %>
  <%= m.label "Miejsca(liczba)" %><br>
  <%= m.text_field :seats_number, class: "input-style" %>
  <%= m.label "Nagroda" %><br>
  <%= m.text_field :price, class: "input-style" %>
  <%= m.label "Gra" %><br>
  <%= m.collection_select :game_id, Game.all, :id, :name, {prompt: "Wybierz"},{ class: "select-tab"} %>
  <%= m.label "Zjazd" %><br>
  <%= m.collection_select :convention_id, Convention.all, :id, :name, {prompt: "Wybierz"}, {class: "select-tab"}  %>

  <%= m.submit "Accept", class: 'submit-style'%>

<%end%>

</body>

app/views/matches/index.html.erb
<body class="matches">

  <% if flash[:error] %>
    <div class="message-box"><%=flash[:error] %></div>
  <%end%>
  <ul class="title-list">
    <li class="title-ele"> Czas </li>
    <li class="title-ele"> Liczba miejsc </li>
    <li class="title-ele"> Prize </li>
    <li class="title-ele"> Gra </li>
    <li class="title-ele"> zjazd </li>
    <li class="title-ele"> Delete </li>
    <li class="title-ele"> Show </li>
    <li class="title-ele"> Edit </li>
  </ul>
<% @all_matches.each do |m| %>
<ul class="name-list">
  <li class="name-list"><div class="name-list"><%= m.time %></div> </li>
  <li class="name-list"><div class="name-list"><%= m.seats_number %> </div></li>
  <li class="name-list"><div class="name-list"><%= m.price %></div> </li>
  <li class="name-list"><div class="name-list"><%= Game.find(m.game_id).name %></div> </li>
  <li class="name-list"><div class="name-list"><%= Convention.find(m.convention_id).name %></div> </li>
  <li class="name-list"><div class="name-list"><%=link_to("Usuń", match_path(m), method: :delete) %></div> </li>
  <li class="name-list"><div class="name-list"><%=link_to("Wyświetl", match_path(m)) %></div> </li>
  <li class="name-list"><div class="name-list"><%= link_to("Edytuj",edit_match_path(m)) %></div> </li>
    <br>
    <br>
</ul>
<%end%>
</body>

app/views/matches/new.html.erb
<body class="matches">
<%= form_for @match do |m| %>
<%if @match.errors.any? %>
<% @match.errors.each do |attr,msg|  %>
<div class="message-box"><%=msg%></div>
<% end %>
<%end %>
  <%= m.label "Czas" %><br>
  <%= m.text_field :time, class: "input-style" %>
  <%= m.label "Miejsca(liczba)" %><br>
  <%= m.text_field :seats_number, class: "input-style" %>
  <%= m.label "Nagroda" %><br>
  <%= m.text_field :price, class: "input-style" %>
  <%= m.label "Gra" %><br>
  <%= m.collection_select :game_id, Game.all, :id, :name, {prompt: "Wybierz"},{ class: "select-tab"} %>
  <%= m.label "Zjazd" %><br>
  <%= m.collection_select :convention_id, Convention.all, :id, :name, {prompt: "Wybierz"}, {class: "select-tab"}  %>

  <%= m.submit "Accept", class: 'submit-style'%>

<%end%>

</body>

app/views/matches/search.html.erb
<body class="match">
<center><p1> Wyszukiwanie: </p1></center>
<ul class="title-list">
  <li class="title-ele"> Czas </li>
  <li class="title-ele"> Liczba miejsc </li>
  <li class="title-ele"> Prize </li>
  <li class="title-ele"> Gra </li>
  <li class="title-ele"> Zjazd </li>
</ul>

<% @match.each do |m| %>
<ul class="name-list">
<li class="name-list"><div class="name-list"><%= m.time %></div> </li>
<li class="name-list"><div class="name-list"><%= m.seats_number %> </div></li>
<li class="name-list"><div class="name-list"><%= m.price %></div> </li>
<li class="name-list"><div class="name-list"><%= Game.find(m.game_id).name %></div> </li>
<li class="name-list"><div class="name-list"><%= Convention.find(m.convention_id).name %></div> </li>
<li class="name-list"><div class="name-list"><%=link_to("Usuń", match_path(m), method: :delete) %></div> </li>
<li class="name-list"><div class="name-list"><%=link_to("Wyświetl", match_path(m)) %></div> </li>
<li class="name-list"><div class="name-list"><%= link_to("Edytuj",edit_match_path(m)) %></div> </li>
  <br>
  <br>
</ul>
<%end%>
</body>

app/views/matches/show.html.erb
<body class="matches">
<center >
  <div class="stat-box">
<div> Czas: <%= @match.time %> </div>
<div> Liczba miejsc: <%=@match.seats_number %> </div>
<div> Nagroda: <%=@match.price %> </div>
<div> Nazwa Gry: <%= Game.find(@match.game_id).name %> </div>
<div> Nazwa zjazdu: <%= Convention.find(@match.convention_id).name %> </div>
</div>
</center>
<%= link_to("Wróć", matches_path) %>
</body>