config/routes.rb
Rails.application.routes.draw do
  root 'pages#show'
  get 'conventions/search', to: 'conventions#search'
  get 'games/search', to: 'games#search'
  get 'matches/search', to: 'matches#search'
  get 'participations/search', to: 'participations#search'
  get 'players/search', to: 'players#search'
  get 'teams/search', to: 'teams#search'
  
  resources :pages, :only=>:show
  resources :games
  resources :teams
  resources :players
  resources :conventions
  resources :matches
  resources :participations
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Games</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <ul class="pasek">
<li><%=link_to("Gracze",players_path,id: "menu",class: "player") %></li><li><%=link_to("Drużyny",teams_path,id: "menu",class: "teams") %></li><li><%=link_to("Zjazdy",conventions_path,id: "menu",class: "conventions") %></li><li><%=link_to("Gry",games_path,id: "menu",class: "games") %></li><li><%=link_to("Rozgrywki",matches_path,id: "menu",class: "matches") %></li><li><%= link_to("Uczestnictwa", participations_path, id: "menu", class: "participation") %> </li>

</ul>
<%= yield %>
</body>
</html>

app/views/layouts/conventions.html.erb
<html>
<head>
  <title>Games</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <ul class="pasek">
<li class="pasek"><%=link_to("S",root_path,id: "menu",class: "page") %></li><li class="pasek"><%=link_to("Gracze",players_path,id: "menu",class: "player") %></li><li class="pasek"><%=link_to("Drużyny",teams_path,id: "menu",class: "teams") %></li><li class="pasek"><%=link_to("Zjazdy",conventions_path,id: "menu",class: "conventions") %></li><li class="pasek"><%=link_to("Gry",games_path,id: "menu",class: "games") %></li><li class="pasek"><%=link_to("Rozgrywki",matches_path,id: "menu",class: "matches") %></li><li class="pasek"><%= link_to("Uczestnictwa", participations_path, id: "menu", class: "participation") %> </li>
</ul>
<ul class="side-menu">
<li class="side-menu"><%= link_to("Nowe",new_convention_path,class: "side-menu") %></li>
<%= form_tag({:controller => 'conventions', :action => 'search'},:method => 'get') do%>
  <li style="float: right"><%= submit_tag "Search" ,class: "search-button"%> </li>
  <li style="float: right"><%= text_field_tag "text",nil, class: "search-input-style" %></li>

<%end%>
</ul>
<%= yield %>
</body>
</html>

app/views/layouts/games.html.erb
<html>
<head>
  <title>Games</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <ul class="pasek">
<li class="pasek"><%=link_to("S",root_path,id: "menu",class: "page") %></li><li class="pasek"><%=link_to("Gracze",players_path,id: "menu",class: "player") %></li><li class="pasek"><%=link_to("Drużyny",teams_path,id: "menu",class: "teams") %></li><li class="pasek"><%=link_to("Zjazdy",conventions_path,id: "menu",class: "conventions") %></li><li class="pasek"><%=link_to("Gry",games_path,id: "menu",class: "games") %></li><li class="pasek"><%=link_to("Rozgrywki",matches_path,id: "menu",class: "matches") %></li><li class="pasek"><%= link_to("Uczestnictwa", participations_path, id: "menu", class: "participations") %> </li>
</ul>
<ul class="side-menu">
<li class="side-menu"><%= link_to("Nowe",new_game_path,class: "side-menu") %></li>
<%= form_tag({:controller => 'games',:action => 'search'},:method => 'get') do%>
  <li style="float: right"><%= submit_tag "Search", class: "search-button" %></li>
  <li style="float: right"><%= text_field_tag "text",nil,class: "search-input-style"%></li>
<%end%>
</ul>
<%= yield %>
</body>
</html>

app/views/layouts/matches.html.erb
<html>
<head>
  <title>Games</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <ul class="pasek">
<li class="pasek"><%=link_to("S",root_path,id: "menu",class: "page") %></li><li class="pasek"><%=link_to("Gracze",players_path,id: "menu",class: "player") %></li><li class="pasek"><%=link_to("Drużyny",teams_path,id: "menu",class: "teams") %></li><li class="pasek"><%=link_to("Zjazdy",conventions_path,id: "menu",class: "conventions") %></li><li class="pasek"><%=link_to("Gry",games_path,id: "menu",class: "games") %></li><li class="pasek"><%=link_to("Rozgrywki",matches_path,id: "menu",class: "matches") %></li><li class="pasek"><%= link_to("Uczestnictwa", participations_path, id: "menu", class: "participation") %> </li>
</ul>
<ul class="side-menu">
<li class="side-menu"><%= link_to("Nowe",new_match_path,class: "side-menu") %></li>
<%=form_tag({:controller => 'matches', :action => 'search'},:method => 'get') do%>
  <li style="float: right"><%=submit_tag "Search", class: "search-button"%></li>
  <li style="float: right"><%=text_field_tag "text",nil, class: "search-input-style" %><li>
<%end%>
</ul>
<%= yield %>
</body>
</html>

app/views/layouts/pages.html.erb
<html>
<head>
  <title>Games</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <ul class="pasek">
<li class="pasek"><%=link_to("S",root_path,id: "menu",class: "page") %></li><li class="pasek"><%=link_to("Gracze",players_path,id: "menu",class: "player") %></li><li class="pasek"><%=link_to("Drużyny",teams_path,id: "menu",class: "teams") %></li><li class="pasek"><%=link_to("Zjazdy",conventions_path,id: "menu",class: "conventions") %></li><li class="pasek"><%=link_to("Gry",games_path,id: "menu",class: "games") %></li><li class="pasek"><%=link_to("Rozgrywki",matches_path,id: "menu",class: "matches") %></li><li class="pasek"><%= link_to("Uczestnictwa", participations_path, id: "menu", class: "participation") %> </li>
</ul>
<%= yield %>
</body>
</html>

app/views/layouts/participations.html.erb
<html>
<head>
  <title>Games</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <ul class="pasek">
<li class="pasek"><%=link_to("S",root_path,id: "menu",class: "page") %></li><li class="pasek"><%=link_to("Gracze",players_path,id: "menu",class: "player") %></li><li class="pasek"><%=link_to("Drużyny",teams_path,id: "menu",class: "teams") %></li><li class="pasek"><%=link_to("Zjazdy",conventions_path,id: "menu",class: "conventions") %></li><li class="pasek"><%=link_to("Gry",games_path,id: "menu",class: "games") %></li><li class="pasek"><%=link_to("Rozgrywki",matches_path,id: "menu",class: "matches") %></li><li class="pasek"><%= link_to("Uczestnictwa", participations_path, id: "menu", class: "participations") %> </li>
</ul>
<ul class="side-menu">
  <li class="side-menu"><%=link_to("Nowe",new_participation_path,class: "side-menu") %></li>
  <%= form_tag({:controller => 'participations',:action => 'search'},:method => 'get') do%>
    <li style="float: right"><%= submit_tag "Search", class: "search-button" %></li>
    <li style="float: right"><%= text_field_tag "text", nil, class: "search-input-style" %></li>
  <%end%>
</ul>
<%= yield %>
</body>
</html>

app/views/layouts/players.html.erb
<html>
<head>
  <title>Games</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <ul class="pasek">
<li class="pasek"><%=link_to("S",root_path,id: "menu",class: "page") %></li><li class="pasek"><%=link_to("Gracze",players_path,id: "menu",class: "player") %></li><li class="pasek"><%=link_to("Drużyny",teams_path,id: "menu",class: "teams") %></li><li class="pasek"><%=link_to("Zjazdy",conventions_path,id: "menu",class: "conventions") %></li><li class="pasek"><%=link_to("Gry",games_path,id: "menu",class: "games") %></li><li class="pasek"><%=link_to("Rozgrywki",matches_path,id: "menu",class: "matches") %></li><li class="pasek"><%= link_to("Uczestnictwa", participations_path, id: "menu", class: "participation") %> </li>
</ul>
<ul class="side-menu">
<li class="side-menu"><%= link_to("Nowe",new_player_path,class: "side-menu") %></li>
<%= form_tag({:controller => 'players', :action => 'search'},:method => 'get') do %>
    <li style="float: right"><%= submit_tag "Search", class: "search-button" %></li>
  <li style="float: right"><%= text_field_tag "text", nil, class: "search-input-style" %></li>
<%end%>
</ul>
<%= yield %>
</body>
</html>

app/views/layouts/teams.html.erb
<html>
<head>
  <title>Games</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <ul class="pasek">
<li class="pasek"><%=link_to("S",root_path,id: "menu",class: "page") %></li><li class="pasek"><%=link_to("Gracze",players_path,id: "menu",class: "player") %></li><li class="pasek"><%=link_to("Drużyny",teams_path,id: "menu",class: "teams") %></li><li class="pasek"><%=link_to("Zjazdy",conventions_path,id: "menu",class: "conventions") %></li><li class="pasek"><%=link_to("Gry",games_path,id: "menu",class: "games") %></li><li class="pasek"><%=link_to("Rozgrywki",matches_path,id: "menu",class: "matches") %></li><li class="pasek"><%= link_to("Uczestnictwa", participations_path, id: "menu", class: "participation") %> </li>
</ul>
<ul class="side-menu">
<li class="side-menu"><%= link_to("Nowe",new_team_path,class: "side-menu") %></li>
<%= form_tag({:controller => 'teams', :action => 'search'},:method => 'get') do %>
  <li style="float: right"><%= submit_tag "Search", class: "search-button" %> </li>
  <li style="float: right"><%= text_field_tag "text", nil, class: "search-input-style"%></li>
<%end%>
</ul>
<%= yield %>
</body>
</html>